class Commands(object):
	"""
	Contains the IRC commands and reply codes
	"""
	COMMAND_ERR_NEEDMOREPARAMS = "461"

	USER_COMMAND = "USER"
	NICK_COMMAND = "NICK"
	NICK_ERR_NONICKNAMEGIVEN = "431"
	NICK_ERR_ERRONEUSNICKNAME = "432"
	NICK_ERR_NICKNAMEINUSE = "433"
	NICK_ERR_NICKCOLLISION = "436"

	AUTH_ERR_ALREADYREGISTRED = "462"

	JOIN_COMMAND = "JOIN"
	JOIN_ERR_NOSUCHCHANNEL = "403"
	JOIN_ERR_CHANNELISFULL = "471"
	JOIN_ERR_INVITEONLYCHAN = "473"
	JOIN_ERR_BANNEDFROMCHAN = "474"
	JOIN_ERR_BADCHANNELKEY = "475"
	JOIN_RPL_TOPIC = "332"

	PART_COMMAND = "PART"
	QUIT_COMMAND = "QUIT"
	PRIVMSG_COMMAND = "PRIVMSG"

	WHO_COMMAND = "WHO"
	WHO_RPL_WHOREPLY = "352"
	WHO_RPL_ENDOFWHO = "315"

	NICKSERV_IDENTIFY_COMMAND = "IDENTIFY"
	NICKSERV_RPL_LOGGEDIN = "900"
	NICKSERV_RPL_LOGGEDOUT = "901"
	NICKSERV_ERR_NICKLOCKED = "902"

	SASL_AUTHENTICATE_COMMAND = "AUTHENTICATE"
	SASL_RPL_SASLSUCCESS = "903"
	SASL_ERR_SASLFAIL = "904"
	SASL_ERR_SASLTOOLONG = "905"
	SASL_ERR_SASLABORTED = "906"
	SASL_ERR_SASLALREADY = "907"
	SASL_RPL_SASLMECHS = "908"
